DROP DATABASE IF EXISTS chirper_db;
CREATE DATABASE chirper_db;

USE chirper_db;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(30) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USER_ID)
);



DROP TABLE IF EXISTS CHAT;
CREATE TABLE CHAT (
    CHAT_ID INT AUTO_INCREMENT,
    CHAT_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (CHAT_ID)
);

DROP TABLE IF EXISTS USER_CHAT;
CREATE TABLE USER_CHAT(
    USER_ID INT, -- Added automatically by Sequelize
    CHAT_ID INT, -- Added automatically by Sequelize
    IS_OWNER BOOLEAN, -- Needs to be added through the code
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT(CHAT_ID)
);

DROP TABLE IF EXISTS MESSAGES;
CREATE TABLE MESSAGES (
    MESSAGE_ID INT AUTO_INCREMENT,
    MESSAGE_CONTENT VARCHAR(255),
    CHAT_ID INT,
    SENDER_ID INT,
    MESSAGE_SENT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT(CHAT_ID),
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(USER_ID),
    PRIMARY KEY (MESSAGE_ID)
)
INSERT INTO USERS (USERNAME,EMAIL,PASSWORD) VALUES ('FRED', 'TEST@GMAIL.COM', 'AAAAAAAAAA')